# Generated by Django 3.0.5 on 2020-05-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200503_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog/image'),
        ),
    ]
