# Generated by Django 3.0.5 on 2020-05-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('describtion', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='portfolio2/image/')),
                ('urls', models.URLField(blank=True)),
            ],
        ),
    ]
