# Generated by Django 3.0.5 on 2020-05-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project2',
            name='image',
            field=models.ImageField(blank=True, upload_to='portfolio2/image/'),
        ),
    ]
